"""init: restaurants, users, reviews, point_history

Revision ID: 81b11f5b0ef7
Revises: 
Create Date: 2026-08-10 17:13:01.049099

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '81b11f5b0ef7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('geocode_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('biz_type_code', sa.String(length=20), nullable=True),
    sa.Column('is_konapay', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_mobeom', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('konapay_seq', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('konapay_seq')
    )
    op.create_index('ix_restaurants_coords', 'restaurants', ['lat', 'lng'], unique=False)
    op.create_index('ix_restaurants_is_konapay', 'restaurants', ['is_konapay'], unique=False)
    op.create_index('ix_restaurants_is_mobeom', 'restaurants', ['is_mobeom'], unique=False)
    op.create_index('ix_restaurants_name', 'restaurants', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('login_id', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=False),
    sa.Column('is_resident_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('resident_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resident_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('points', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login_id'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('point_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_point_history_user_id', 'point_history', ['user_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('restaurant_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_receipt_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('receipt_image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reviews_restaurant_id', 'reviews', ['restaurant_id'], unique=False)
    op.create_index('ix_reviews_user_id', 'reviews', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reviews_user_id', table_name='reviews')
    op.drop_index('ix_reviews_restaurant_id', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_point_history_user_id', table_name='point_history')
    op.drop_table('point_history')
    op.drop_table('users')
    op.drop_index('ix_restaurants_name', table_name='restaurants')
    op.drop_index('ix_restaurants_is_mobeom', table_name='restaurants')
    op.drop_index('ix_restaurants_is_konapay', table_name='restaurants')
    op.drop_index('ix_restaurants_coords', table_name='restaurants')
    op.drop_table('restaurants')
    # ### end Alembic commands ###
