"""add seasonal_events

Revision ID: 93bd072660e8
Revises: e1a7c9d3b402
Create Date: 2026-08-12 13:07:44.999235

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '93bd072660e8'
down_revision: Union[str, None] = 'e1a7c9d3b402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasonal_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('food_keyword', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('radius_km', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_seasonal_events_dates', 'seasonal_events', ['start_date', 'end_date'], unique=False)
    op.create_index('ix_seasonal_events_type', 'seasonal_events', ['event_type'], unique=False)
    op.create_index('uq_seasonal_events_name_start', 'seasonal_events', ['name', 'start_date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_seasonal_events_name_start', table_name='seasonal_events')
    op.drop_index('ix_seasonal_events_type', table_name='seasonal_events')
    op.drop_index('ix_seasonal_events_dates', table_name='seasonal_events')
    op.drop_table('seasonal_events')
    # ### end Alembic commands ###
