"""add unique constraint on reviews(user_id, restaurant_id)

Revision ID: ace9fc4e4a76
Revises: fc071f0571a4
Create Date: 2026-08-11 23:17:05.946362

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ace9fc4e4a76'
down_revision: Union[str, None] = 'fc071f0571a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_reviews_user_restaurant', 'reviews', ['user_id', 'restaurant_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_reviews_user_restaurant', 'reviews', type_='unique')
    # ### end Alembic commands ###
