"""add reviews.earned_points

Revision ID: cd6f6b896774
Revises: 28b46c37371f
Create Date: 2026-08-12 06:00:17.154826

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'cd6f6b896774'
down_revision: Union[str, None] = '28b46c37371f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('earned_points', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'earned_points')
    # ### end Alembic commands ###
