"""add category/geocode_status indexes and mobeom dedup constraint

Revision ID: fc071f0571a4
Revises: 81b11f5b0ef7
Create Date: 2026-08-11 01:08:42.636208

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'fc071f0571a4'
down_revision: Union[str, None] = '81b11f5b0ef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_restaurants_category', 'restaurants', ['category'], unique=False)
    op.create_index('ix_restaurants_geocode_status', 'restaurants', ['geocode_status'], unique=False)
    op.create_index('uq_restaurants_name_address_no_seq', 'restaurants', ['name', 'address'], unique=True, postgresql_where=sa.text('konapay_seq IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_restaurants_name_address_no_seq', table_name='restaurants', postgresql_where=sa.text('konapay_seq IS NULL'))
    op.drop_index('ix_restaurants_geocode_status', table_name='restaurants')
    op.drop_index('ix_restaurants_category', table_name='restaurants')
    # ### end Alembic commands ###
